blank_issues_enabled: false
contact_links:
  - name: 📖 Contributing Policy
    url: https://github.com/TomGrozev/arangox_ecto/blob/master/CONTRIBUTING.md
    about: "Please read through our contributing policy before opening an issue or pull request"
  - name: ❓ Discussion
    url: https://github.com/TomGrozev/arangox_ecto/discussions
    about: "If you're just looking for help, try starting a discussion instead"
