name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
    test-deploy:
      name: Test and Deploy
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: xinova/arangodb-action@v1
          with:
            arangodb version: 'latest'
        - uses: actions/setup-elixir@v1
          with:
            otp-version: '23'
            elixir-version: '1.10.4'
        - run: mix deps.get
        - run: mix format --check-formatted
        - run: mix clean
        - run: mix compile --warnings-as-errors
        - run: mix credo --strict --ignore design
        - run: mix doctor --summary
        - run: mix test
          env:
            DB_ENDPOINT: 'http://localhost:8529'
        - run: mix hex.publish --yes
          env:
            HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ github.ref }}
              release_name: Release ${{ github.ref }}
              body: |
                Changes in this Release
                - First Change
                - Second Change
              draft: false
              prerelease: false
