name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
    deploy:
      name: Deploy to Hex and create release
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-elixir@v1
          with:
            otp-version: '23'
            elixir-version: '1.11.0'
        - uses: actions/cache@v2
          with:
            path: deps
            key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            restore-keys: |
              ${{ runner.os }}-mix-
        - run: mix deps.get
        - run: mix compile --warnings-as-errors
        - run: mix hex.publish --yes
          env:
            HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
